### ISSUE TITLE
Vlastní cesta ke složce hc-calc

### ISSUE THREAD

**Issue by vaclavpavek** [homecreditcz/widget-calculator#1]
V souboru **appLoader.js** dynamicky načítáte další soubory, ale v rámci naši aplikace chceme mít tyto scripty jinde. Měla by existovat možnost upravit si tuto cestu dle potřeby. Občas máme eshop mimo root tj. je v pod-adresáři.

Navíc vám script generuje relativní cestu místo absolutní tj. ```muj-produkt/hc-calc/``` místo ```/hc-calc/```.

Např. před načtením souborů ```hc-calc/js/resize.js``` a ```hc-calc/js/appLoader.js``` by mohlo být např.

```html
<script>
  var hcCalcDir = '/any/directory/to/hc-calc';
</script>
```

Obecně když už je to takto řešené, tak ```appLoader.js``` by měl načítat všechny potřebné scripty a klidně i CSS. A také by by mohl obsahovat šablonu pro modální okno. Výhodou je snadný update (prostě přehraju zdrojáky).

## část problematického kódu z ```appLoader.js```[29-37]
```js
var script = doc.createElement('script');
script.charset = 'UTF-8';
script.type = 'text/javascript';
script.src = 'hc-calc/js/app.js';
head.appendChild(script);

var resizeScript = doc.createElement('script');
resizeScript.src = 'hc-calc/js/resize.contentWindow.js';
head.appendChild(resizeScript);
```

## PR
Neměl bych problém udělat refaktoring a poslat PR, ale to by repositář musel obsahovat zdrojové soubory a ne binární blob (zip).

**Comment by homecreditcz** [comment]
Děkujeme za podnět, budeme se jím v nejbližší době zabývat.

**Comment by homecreditcz** [comment]
Dobrý den,

Vyšla nova major verze kalkulacky v10, kde je tento problem opraven.

Ticket uzavírame. V připadě problemů prosime založte nový.
