### ISSUE TITLE
Callback při zavření kalkulačky bez výběru splátek

### ISSUE THREAD

**Issue by vaclavpavek** [homecreditcz/widget-calculator#2]
Bylo by dobré aby funkce ```showHcCalc``` přijímala kromě úspěšného callbacku také callback pro případ kdy uživatel nevybere splátky a zavře okno. Obecně by bylo dobré přejít na eventy jako to má Bootstrap s tím, že u úspěšného callbacku by se předávali ještě data z kalkulačky.

**Comment by homecreditcz** [comment]
Děkujeme za podnět, budeme se jím v nejbližší době zabývat.

**Comment by homecreditcz** [comment]
Dobrý den,

Vyšla nova major verze kalkulacky v10, kde je tento problem opraven.

Ticket uzavírame. V připadě problemů prosime založte nový.
