### ISSUE TITLE
SK apikey

### ISSUE THREAD

**Issue by tomasbarta** [homecreditcz/widget-calculator#3]
Po otevření html souboru ve slovenské verzi widgetu je předvolen APIKey=calculator_test_key_sk. Ten nefunguje, správný je calculator_test_key

**Comment by homecreditcz** [comment]
Dobrý den,

Vyšla nova major verze kalkulacky v10, kde je tento problem opraven.

Ticket uzavírame. V připadě problemů prosime založte nový.
