### ISSUE TITLE
SK baseURL widgetu

### ISSUE THREAD

**Issue by tomasbarta** [homecreditcz/widget-calculator#4]
Widget-calculator/Instalace: je zde uvedena produkční baseURL pouze pro CZ, prosím o doplnění SK baseURL: https://api.homecredit.sk/public/v1/calculator/

**Comment by homecreditcz** [comment]
Dobrý den,

Vyšla nova major verze kalkulacky v10, kde je tento problem opraven.

Ticket uzavírame. V připadě problemů prosime založte nový.
