### ISSUE TITLE
Widget v9 problem

### ISSUE THREAD

**Issue by LuboZ** [homecreditcz/widget-calculator#5]
Po implementacii novej verzie widgetu (SK) dostavame nasledovnu chybu. Rovnaku chybu hadze aj example implementacia dodana priamo s widgetom. 
```
TypeError: Cannot read properties of undefined (reading 'getTranslations')
    at t.get (app.js:1)
    at t.value (app.js:1)
    at app.js:1
    at a.n (app.js:1)
    at a.t._render (app.js:16)
    at a.n (app.js:16)
    at rn.get (app.js:16)
    at rn.run (app.js:16)
    at Zr (app.js:16)
    at Array.<anonymous> (app.js:16)
```

**Comment by mzvarik** [comment]
Píše mi to to samé.
Vůbec nefunguje příkladový skript.
Přišli jste na to?

**Comment by mzvarik** [comment]
OK, je třeba změnit "config.json"
A dát tam pro CZ toto:
"VUE_APP_API_BASE_URL": "https://api.homecredit.cz/public/v1/calculator/"

Úplně bordel s těma adresama a 10 konfigurací...

**Comment by mzvarik** [comment]
Když to hlásí: **TypeError: Cannot read properties of undefined (reading 'getTranslations')**

tak se buď nenačetl "config.json" anebo má špatné hodnoty.

Do appLoader.js je lepší tam dát rovnou celý kód... nechápu proč to načítají externě přes "doc.createElement('script');", akorát je problém s cache a s cestama.

Takto mě to už funguje:
```
	var innerWin = iframe.contentWindow || iframe;
	innerWin.envConfig = {
		"VUE_APP_MODE": "widget",
		"VUE_APP_API_BASE_URL": "https://api.homecredit.cz/public/v1/calculator/",
		"VUE_APP_CULTURE": "cs-CZ",
		"VUE_APP_API_KEY": "calculator_test_key",
		"VUE_APP_PRODUCT_SET_CODE": "COCHCONL",
		"VUE_APP_GTM_CODE": "GTM-NBZD00B",
		"VUE_APP_URL_TURBO": "https://www.homecredit.cz/file-download/2/9/5/3/BA-BONUS-100ZPET-IEK.pdf"
	};
```

**Comment by homecreditcz** [comment]
Dobrý den,

Vyšla nova major verze kalkulacky v10, kde je tento problem opraven.

Ticket uzavírame. V připadě problemů prosime založte nový.
