### ISSUE TITLE
transformCalculationIntoCallback nevracia potrebne parametre

### ISSUE THREAD

**Issue by hauso** [homecreditcz/widget-calculator#6]
V10 Callback _transformCalculationIntoCallback_ vrati iba 

```
{
  preferredInstallment: 129500, // minor units
  preferredDownPayment: 100000, // minor units
  creditAmount: 1300000, // minor units
  creditTotalRepay: 1554000, // minor units
}
```

ostatne parametre chybaju
```  
  legalLine: "Každou žádost posuzujeme...",
  productCode: "COCONL12",
  annualPercentageRate: 22,
  preferredMonths: 12
```
  
cast kodu:
```
transformCalculationIntoCallback(t){return{preferredInstallment:De.convertToMinorUnits(t.installment.amount),preferredDownPayment:De.convertToMinorUnits(t.downpayment),creditAmount:De.convertToMinorUnits(t.installment.amount-t.downpayment),creditTotalRepay:De.convertToMinorUnits(t.paidBack.amount)}}
```

**Comment by homecreditcz** [comment]
Dobrý den, dekujeme za upozornění. Chybějící časti jsme přidali v nejnovější verzi naší kalkulačky. Verze v0.11
https://github.com/homecreditcz/widget-calculator/releases/tag/v0.11

**Comment by hauso** [comment]
Dakujem za update ale parameter 
_annualPercentageRate_ je plneny neexistujucim paramtrom "_t.annualPercentageRate_",
asi sa malo jednat o "t.rpsn" ako vo verzi v.09.
kod:
`annualPercentageRate: t.annualPercentageRate`

**Comment by homecreditcz** [comment]
Dobrý den, dekujeme.
Mělo by začít fungovat správně ve verzi v0.13
